development:
  adapter: mysql
  database: icottage_development
  username: root
  password:
  host: localhost
test:
  adapter: mysql
  database: icottage_test
  username: root
  password:
  host: localhost
production:
  adapter: mysql
  database: icottage
  username: root
  password:
  host: localhost